---
title: "Foreign Policy Issues"
output:
   html_document:
     toc: true
     toc_float: true
---
## Ukraine

During the Ukraine War in 2022, Germany took part in the swift sanctions imposed on Russia by other nations. This included suspending the Nord Stream 2 gas pipeline, which brought Russian oil to Western Europe. Additionally, Germany joined in the no-fly zone for Russian aircraft and sent arms and weapons to Ukraine. 

Sending arms to Ukraine represented a policy shift for Germany, as the law forbids sending weapons to conflict zones. However, policy shift may not set new norms for German behavior in regards to defense, as each similar circumstance is decided on a case by case basis.  

## Immigration

Germany accepted more than one million immigrants and refugees between 2015 and 2016. A majority of these asylum seekers came from the Middle East and North Africa, fleeing violence and turmoil. 

The influx of immigrants sparked backlash from Germany's far right party, Alternative für Deutschland, but Chancellor Angela Merkel held strong in her policy of welcome. 

## Greek Debt Crisis

Rather than a military issue, the Greek debt crisis throughout the 2010s is of economic and diplomatic concern. Amidst the financial hardships in Greece, Germany offered the struggling country a temporary exit from the Eurozone. Proposing such an exist was unprecedented, but thought necessary at the time to ensure that the Euro as a currency would not suffer a collapse and jeopardize the free movement of people, goods, services, and capital throughout the European Union. The so-called 'Grexit' never came to pass. 

Germany was one of the major European creditors of Greece and advocated for many bailouts between 2010 and 2015. But this caused some backlash with the German people, as the bailouts were financed with taxpayer money. 