---
title: "Political Party Views"
output:
   html_document:
     toc: true
     toc_float: true
---
## Major Parties and their Foreign Policy Platforms

### Christian Democratic Union (CDU/CSU)

The CDU endorses Germany's role as a leader in both the EU and NATO, and believes that global problems such as human rights and climate change require global solutions. The CDU is committed to democratic values, freedom of religion, rule or law, and human rights at home and across the globe.

### Socialist Demcrats (SPD)

The Socialist Democrats view international organizations as the solutions to the worlds security problems. The EU, UN, and NATO are all essential for the formation of common security policy across the globe. Additionally, the SPD seeks a closer relationship with Russia in order to ensure security.

### Free Democrats (FDP)

The Free Democrats believe in the strength of the European Parliament and promote  a common security and defense policy within the EU. They are also committed to NATO and wish for Germany to negotiate with nuclear powers towards disarmament and arms control. According to the FDP, a better use of time and resources is to work towards peace and demilitarization. To do this, FDP proposes a prohibition of arms exports and the conversion of the arms industry into civilian production, which includes weapons conversion. 

### The Left Party

The Left Party holds an anti-war position and wants the Bundeswher to withdraw from all foreign operations. The Left advocates for Germany's continued membership in the EU, but desires policy and structural shifts within the organization of the EU. The Left also wishes to dissolve NATO and create a new security alliance that includes Russia. 

### Greens of Germany

The Greens wish to increase transparency within the European Union, and strengthen the democratic aspects of the EU. The Greens also support a strong transatlantic partnership and commitment to NATO as a means of ensuring peace and security.

### Alternative für Deutschland (AfD)

Alternative für Deutschland is ostensibly against multilateral institutions for security. AfD wishes for Germany to leave the European Union and gain a permanent seat on the UN Security Council. They oppose German intervention abroad or contribution of troops to international military forces. Overall, AfD wishes to re-nationalize security in Germany and use German forces internally rather than abroad.

## General Consensus

German foreign policy is most influenced by the four major and centrist parties: CDU, SPD, FDP, and the Greens. All four prioritize a multilateral security strategy. Specifically, the general trend is for greater European integration and the recognition of the importance of NATO and transatlantic relationships for security. 

The Left Party and AfD have  voices in the Bundestag (German parliament), but neither have enough of a presence to be essential in coalitions passing legislation. Thus they have less influence over foreign policy. 
