---
title: "References"
output: html_document
---

"Germany." . https://european-union.europa.eu/principles-countries-history/country-profiles/germany_en.

"Germany and the Euro." . https://ec.europa.eu/info/business-economy-euro/euro-area/euro/eu-countries-and-euro/germany-and-euro_en.

"Germany’s Foreign and European Policy Principles." . https://www.auswaertiges-amt.de/en/aussenpolitik/themen/policy-principles/229790.

"History of German Foreign Policy." . https://en.wikipedia.org/wiki/History_of_German_foreign_policy#1945–1990.

"History of the European Union 1945-59." . https://european-union.europa.eu/principles-countries-history/history-eu/1945-59_en.

"The Minister of Defense." . https://www.bmvg.de/en/organisation/minister-of-defence-christine-lambrecht.

"Structure and Organization." . https://www.bmvg.de/en/organisation.

"United Nations
." . https://www.un.org/en/about-us/member-states/germany.

Central Intelligence Agency. "Germany
." . https://www.cia.gov/the-world-factbook/countries/germany/#geography.

Encyclopedia Britannica. "Germany." . https://www.britannica.com/place/Germany.

Hasselbach, Christoph. "Five Years on: How Germany's Refugee Policy has Fared." Dw, August 25, 2020. https://www.dw.com/en/five-years-on-how-germanys-refugee-policy-has-fared/a-54660166.

Hasselbach, Christoph. "Ukraine-Russia War Triggers Major German Policy Changes." Dw, January 3, 2022. https://apple.news/ANAvrs5OkSISUkw0R1yj-WA.

Herszenhorn, David M., Lili Bayer, and Hans Von Der Burchard. "Germany to Send Ukraine Weapons in Historic Shift on Military Aid." Politico, February 26, 2022. https://www.politico.eu/article/ukraine-war-russia-germany-still-blocking-arms-supplies/.

Irwin, Neil. "How Germany Prevailed in the Greek Bailout." New York Times, July 29, 2015. https://www.nytimes.com/2015/07/30/world/europe/how-germany-prevailed-in-the-greek-bailout.html.

Jackson, Lauren and Tara Godvin. "On the Path to Day X: The Return of Germany's Far Right." New York Times, July 6, 2021. https://www.nytimes.com/2021/06/25/world/europe/germany-nazi-far-right.html.

Kaufman, Joyce P. and Joyce P. Kaufman. Introduction to International Relations. Lanham, MD: The Rowman & Littlefield Publishing Group, 2013. http://portal.igpublish.com/iglibrary/search/ROWMANB0007844.html.

Martinez, Andres. "Don'T Blame Germany for Greece's Debt Crisis." Time Magazine, July 31, 2015.

Metzger, David. "A Post-Merkel German Foreign Policy: A Look into the Parties’ Election Agendas." . https://securingdemocracy.gmfus.org/a-post-merkel-german-foreign-policy-a-look-into-the-parties-election-agendas/.

Reuters Staff. "Germany to Host G7 Meeting on Ukraine Invasion's Impact on Food Security." Reuters, March 7, 2022a. https://apple.news/ArTHJBV1cS2KMZQ5UhmeSgg.

Reuters Staff. "Germany Won'T Send Warplanes to Ukraine, Eyes Energy Cooperation with Canada." Reuters, March 9, 2022b. https://apple.news/ANaCLlc1gQhSCmzBOMumvzg.

Social Democrats. Hamburg Programme: Social Democrats.

Turak, Natasha. "Germany Announces Major Defense Policy Shift in Face of Russia's Ukraine Invasion." February 27, 2022. https://apple.news/AVqkpZt34R6qFYpVsDBFExw.

# Image Links

https://media.giphy.com/media/VN7qpUiqxl6UHGD1RB/giphy.gif

https://media.giphy.com/media/d55vWXcvPtf8C5zEva/giphy.gif

https://www.dissco.eu/dissco-rising/logo-eu-eu-logo/

https://www.britannica.com/topic/North-Atlantic-Treaty-Organization

https://en.wikipedia.org/wiki/Allied-occupied_Germany

https://en.wikipedia.org/wiki/Berlin_Wall

https://qz.com/1461905/german-chancellor-angela-merkel-calls-for-european-army/

https://www.ardaudiothek.de/episode/aktuelle-interviews/klimaschutzgesetz-svenja-schulze-bundesumweltministerin-spd/bayern-2/90527606/

https://www.reuters.com/world/africa/german-defence-minister-very-sceptical-about-mali-mission-2022-02-06/

https://ces.fas.harvard.edu/people/annalena-baerbock

https://media.giphy.com/media/smopgv59WW2Bn541Zg/giphy.gif



